# Generated by Django 5.1.15 on 2026-06-25 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0022_normalize_localfiles_paths"),
        ("projects", "0035_projectmember_role"),
        ("tasks", "0060_add_allow_skip_to_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="OssExportStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync finished time",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Count of tasks synced last time",
                        null=True,
                        verbose_name="last sync count",
                    ),
                ),
                (
                    "last_sync_job",
                    models.CharField(
                        blank=True,
                        help_text="Last sync job ID",
                        max_length=256,
                        null=True,
                        verbose_name="last_sync_job",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="initialized",
                        max_length=64,
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback report for the last failed sync",
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Meta and debug information about storage processes",
                        null=True,
                        verbose_name="meta",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage title",
                        max_length=256,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "synchronizable",
                    models.BooleanField(
                        default=True,
                        help_text="If storage can be synced",
                        verbose_name="synchronizable",
                    ),
                ),
                (
                    "can_delete_objects",
                    models.BooleanField(
                        blank=True,
                        help_text="Deletion from storage enabled",
                        null=True,
                        verbose_name="can_delete_objects",
                    ),
                ),
                (
                    "bucket",
                    models.TextField(
                        blank=True,
                        help_text="S3 bucket name",
                        null=True,
                        verbose_name="bucket",
                    ),
                ),
                (
                    "prefix",
                    models.TextField(
                        blank=True,
                        help_text="S3 bucket prefix",
                        null=True,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "regex_filter",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage regex for filtering objects",
                        null=True,
                        verbose_name="regex_filter",
                    ),
                ),
                (
                    "use_blob_urls",
                    models.BooleanField(
                        default=False,
                        help_text="Interpret objects as BLOBs and generate URLs",
                        verbose_name="use_blob_urls",
                    ),
                ),
                (
                    "aws_access_key_id",
                    models.TextField(
                        blank=True,
                        help_text="AWS_ACCESS_KEY_ID",
                        null=True,
                        verbose_name="aws_access_key_id",
                    ),
                ),
                (
                    "aws_secret_access_key",
                    models.TextField(
                        blank=True,
                        help_text="AWS_SECRET_ACCESS_KEY",
                        null=True,
                        verbose_name="aws_secret_access_key",
                    ),
                ),
                (
                    "aws_session_token",
                    models.TextField(
                        blank=True,
                        help_text="AWS_SESSION_TOKEN",
                        null=True,
                        verbose_name="aws_session_token",
                    ),
                ),
                (
                    "aws_sse_kms_key_id",
                    models.TextField(
                        blank=True,
                        help_text="AWS SSE KMS Key ID",
                        null=True,
                        verbose_name="aws_sse_kms_key_id",
                    ),
                ),
                (
                    "region_name",
                    models.TextField(
                        blank=True,
                        help_text="AWS Region",
                        null=True,
                        verbose_name="region_name",
                    ),
                ),
                (
                    "s3_endpoint",
                    models.TextField(
                        blank=True,
                        help_text="S3 Endpoint",
                        null=True,
                        verbose_name="s3_endpoint",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="A unique integer value identifying this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OssExportStorageLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_exists",
                    models.BooleanField(
                        default=True,
                        help_text="Whether object under external link still exists",
                        verbose_name="object exists",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update time",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="tasks.annotation",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="io_storages.ossexportstorage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OssImportStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync finished time",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Count of tasks synced last time",
                        null=True,
                        verbose_name="last sync count",
                    ),
                ),
                (
                    "last_sync_job",
                    models.CharField(
                        blank=True,
                        help_text="Last sync job ID",
                        max_length=256,
                        null=True,
                        verbose_name="last_sync_job",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="initialized",
                        max_length=64,
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback report for the last failed sync",
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Meta and debug information about storage processes",
                        null=True,
                        verbose_name="meta",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage title",
                        max_length=256,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "synchronizable",
                    models.BooleanField(
                        default=True,
                        help_text="If storage can be synced",
                        verbose_name="synchronizable",
                    ),
                ),
                (
                    "bucket",
                    models.TextField(
                        blank=True,
                        help_text="S3 bucket name",
                        null=True,
                        verbose_name="bucket",
                    ),
                ),
                (
                    "prefix",
                    models.TextField(
                        blank=True,
                        help_text="S3 bucket prefix",
                        null=True,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "regex_filter",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage regex for filtering objects",
                        null=True,
                        verbose_name="regex_filter",
                    ),
                ),
                (
                    "use_blob_urls",
                    models.BooleanField(
                        default=False,
                        help_text="Interpret objects as BLOBs and generate URLs",
                        verbose_name="use_blob_urls",
                    ),
                ),
                (
                    "aws_access_key_id",
                    models.TextField(
                        blank=True,
                        help_text="AWS_ACCESS_KEY_ID",
                        null=True,
                        verbose_name="aws_access_key_id",
                    ),
                ),
                (
                    "aws_secret_access_key",
                    models.TextField(
                        blank=True,
                        help_text="AWS_SECRET_ACCESS_KEY",
                        null=True,
                        verbose_name="aws_secret_access_key",
                    ),
                ),
                (
                    "aws_session_token",
                    models.TextField(
                        blank=True,
                        help_text="AWS_SESSION_TOKEN",
                        null=True,
                        verbose_name="aws_session_token",
                    ),
                ),
                (
                    "aws_sse_kms_key_id",
                    models.TextField(
                        blank=True,
                        help_text="AWS SSE KMS Key ID",
                        null=True,
                        verbose_name="aws_sse_kms_key_id",
                    ),
                ),
                (
                    "region_name",
                    models.TextField(
                        blank=True,
                        help_text="AWS Region",
                        null=True,
                        verbose_name="region_name",
                    ),
                ),
                (
                    "s3_endpoint",
                    models.TextField(
                        blank=True,
                        help_text="S3 Endpoint",
                        null=True,
                        verbose_name="s3_endpoint",
                    ),
                ),
                (
                    "presign",
                    models.BooleanField(
                        default=True,
                        help_text="Generate presigned URLs",
                        verbose_name="presign",
                    ),
                ),
                (
                    "presign_ttl",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Presigned URLs TTL (in minutes)",
                        verbose_name="presign_ttl",
                    ),
                ),
                (
                    "recursive_scan",
                    models.BooleanField(
                        default=False,
                        help_text="Perform recursive scan over the bucket content",
                        verbose_name="recursive scan",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="A unique integer value identifying this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OssImportStorageLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.TextField(help_text="External link key", verbose_name="key"),
                ),
                (
                    "object_exists",
                    models.BooleanField(
                        default=True,
                        help_text="Whether object under external link still exists",
                        verbose_name="object exists",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "row_group",
                    models.IntegerField(
                        blank=True, help_text="Parquet row group", null=True
                    ),
                ),
                (
                    "row_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Parquet row index, or JSON[L] object index",
                        null=True,
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="io_storages.ossimportstorage",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
