import { t } from "@humansignal/core";
export const DEFAULT_HOTKEYS = [
  // Annotation Controls
  {
    id: 100,
    section: "annotation",
    element: "annotation:submit",
    label: t("Submit Annotation"),
    key: "ctrl+enter",
    description: t("Submit the current annotation"),
    active: true,
  },
  {
    id: 200,
    section: "annotation",
    element: "annotation:skip",
    label: t("Skip Task"),
    key: "ctrl+space",
    description: t("Skip the current task"),
    active: true,
  },
  {
    id: 300,
    section: "annotation",
    element: "annotation:undo",
    label: t("Undo"),
    key: "ctrl+z",
    description: t("Undo last action"),
    active: true,
  },
  {
    id: 400,
    section: "annotation",
    element: "annotation:redo",
    label: t("Redo"),
    key: "ctrl+shift+z",
    description: t("Redo previously undone action"),
    active: true,
  },

  // Data Manager
  {
    id: 500,
    section: "data_manager",
    element: "dm.focus-previous",
    label: t("Focus Previous Task"),
    key: "shift+up",
    description: t("Move focus to the previous task"),
    active: true,
  },
  {
    id: 600,
    section: "data_manager",
    element: "dm.focus-next",
    label: t("Focus Next Task"),
    key: "shift+down",
    description: t("Move focus to the next task"),
    active: true,
  },
  {
    id: 700,
    section: "data_manager",
    element: "dm.close-labeling",
    label: t("Focus Closed Task"),
    key: "shift+left",
    description: t("Focus on the closed task column"),
    active: true,
  },
  {
    id: 800,
    section: "data_manager",
    element: "dm.open-labeling",
    label: t("Focus Open Task"),
    key: "shift+right",
    description: t("Focus on the open task column"),
    active: true,
  },
  {
    id: 900,
    section: "data_manager",
    element: "dm.toggle-bulk-sidebar-minimization",
    label: t("Toggle Bulk Sidebar"),
    key: "shift+.",
    description: t("Minimize or expand bulk actions sidebar"),
    active: true,
  },

  // Region Management
  {
    id: 1100,
    section: "regions",
    element: "region:delete-all",
    label: t("Delete All Regions"),
    key: "ctrl+backspace",
    description: t("Remove all regions"),
    active: true,
  },
  {
    id: 1200,
    section: "regions",
    element: "region:focus",
    label: t("Focus First Region"),
    key: "enter",
    description: t("Move focus to the first focusable region"),
    active: true,
  },
  {
    id: 1300,
    section: "regions",
    element: "region:relation",
    label: t("Create Region Relation"),
    key: "alt+r",
    description: t("Create a relation between selected regions"),
    active: true,
  },
  {
    id: 1400,
    section: "regions",
    element: "region:visibility",
    label: t("Toggle Region Visibility"),
    key: "alt+h",
    description: t("Show or hide the selected region"),
    active: true,
  },
  {
    id: 1500,
    section: "regions",
    element: "region:visibility-all",
    label: t("Toggle All Region Visibility"),
    key: "ctrl+h",
    description: t("Show or hide all regions"),
    active: true,
  },
  {
    id: 1600,
    section: "regions",
    element: "region:lock",
    label: t("Lock Region"),
    key: "alt+l",
    description: t("Lock or unlock the selected region"),
    active: true,
  },
  {
    id: 1700,
    section: "regions",
    element: "region:meta",
    label: t("Edit Region Metadata"),
    key: "alt+m",
    description: t("Edit metadata for selected region"),
    active: true,
  },
  {
    id: 1800,
    section: "regions",
    element: "region:unselect",
    label: t("Unselect Region"),
    key: "u",
    description: t("Deselect the currently selected region"),
    active: true,
  },
  {
    id: 1900,
    section: "regions",
    element: "region:exit",
    label: t("Exit Region Mode"),
    key: "escape",
    description: t("Exit relation mode and unselect region"),
    active: true,
  },
  {
    id: 2000,
    section: "regions",
    element: "region:delete",
    label: t("Delete Selected Region"),
    key: "backspace",
    description: t("Delete currently selected region"),
    active: true,
  },
  {
    id: 2100,
    section: "regions",
    element: "region:cycle",
    label: t("Cycle Regions"),
    key: "alt+.",
    description: t("Cycle through all regions"),
    active: true,
  },
  {
    id: 2200,
    section: "regions",
    element: "region:duplicate",
    label: t("Duplicate Region"),
    key: "ctrl+d",
    description: t("Create a copy of the selected region"),
    active: true,
  },
  {
    id: 2300,
    section: "regions",
    element: "segment:delete",
    label: t("Delete Segment"),
    key: "delete",
    description: t("Delete selected segment"),
    active: true,
  },

  // Editor - Audio Controls
  {
    id: 2400,
    section: "audio",
    element: "audio:back",
    label: t("Rewind 1 Second"),
    key: "ctrl+b",
    description: t("Rewind the audio by 1 second"),
    active: true,
  },
  {
    id: 2500,
    section: "audio",
    element: "audio:playpause",
    label: t("Play / Pause Audio"),
    key: "ctrl+p",
    description: t("Toggle audio playback"),
    active: true,
  },
  {
    id: 2600,
    section: "audio",
    element: "audio:step-backward",
    label: t("Step Back"),
    key: "alt+a",
    description: t("Step back one frame"),
    active: true,
  },
  {
    id: 2700,
    section: "audio",
    element: "audio:step-forward",
    label: t("Step Forward"),
    key: "alt+d",
    description: t("Step forward one frame"),
    active: true,
  },

  // Editor - Video Controls
  {
    id: 2800,
    section: "video",
    element: "media:playpause",
    label: t("Play / Pause Video"),
    key: "ctrl+alt+space",
    description: t("Toggle video playback"),
    active: true,
  },
  {
    id: 2900,
    section: "video",
    element: "media:step-backward",
    label: t("Step Back"),
    key: "alt+left",
    description: t("Step one frame backward"),
    active: true,
  },
  {
    id: 3000,
    section: "video",
    element: "media:step-forward",
    label: t("Step Forward"),
    key: "alt+right",
    description: t("Step one frame forward"),
    active: true,
  },
  {
    id: 3100,
    section: "video",
    element: "video:keyframe-backward",
    label: t("Previous Keyframe"),
    key: "ctrl+alt+left",
    description: t("Jump to previous keyframe"),
    active: true,
  },
  {
    id: 3200,
    section: "video",
    element: "video:keyframe-forward",
    label: t("Next Keyframe"),
    key: "ctrl+alt+right",
    description: t("Jump to next keyframe"),
    active: true,
  },
  {
    id: 3300,
    section: "video",
    element: "video:backward",
    label: t("Seek Backward"),
    key: "alt+left",
    description: t("Seek video backward"),
    active: true,
  },
  {
    id: 3400,
    section: "video",
    element: "video:rewind",
    label: t("First Frame"),
    key: "shift+ctrl+alt+left",
    description: t("Jump to first frame"),
    active: true,
  },
  {
    id: 3500,
    section: "video",
    element: "video:forward",
    label: t("Seek Forward"),
    key: "shift+alt+right",
    description: t("Seek video forward"),
    active: true,
  },
  {
    id: 3600,
    section: "video",
    element: "video:fastforward",
    label: t("Last Frame"),
    key: "shift+ctrl+alt+right",
    description: t("Jump to last frame"),
    active: true,
  },
  {
    id: 3700,
    section: "video",
    element: "video:hop-backward",
    label: t("Hop Backward"),
    key: "shift+alt+left",
    description: t("Hop backward quickly"),
    active: true,
  },
  {
    id: 3800,
    section: "video",
    element: "video:hop-forward",
    label: t("Hop Forward"),
    key: "shift+alt+right",
    description: t("Hop forward quickly"),
    active: true,
  },

  // Editor - Time Series Controls
  {
    id: 3900,
    section: "timeseries",
    element: "ts:grow-left",
    label: t("Extend Left"),
    key: "left",
    description: t("Extend the region to the left"),
    active: true,
  },
  {
    id: 4000,
    section: "timeseries",
    element: "ts:grow-right",
    label: t("Extend Right"),
    key: "right",
    description: t("Extend the region to the right"),
    active: true,
  },
  {
    id: 4100,
    section: "timeseries",
    element: "ts:shrink-left",
    label: t("Shrink Left"),
    key: "alt+left",
    description: t("Shrink the region from the left"),
    active: true,
  },
  {
    id: 4200,
    section: "timeseries",
    element: "ts:shrink-right",
    label: t("Shrink Right"),
    key: "alt+right",
    description: t("Shrink the region from the right"),
    active: true,
  },
  {
    id: 4300,
    section: "timeseries",
    element: "ts:grow-left-large",
    label: t("Extend Left (Large)"),
    key: "shift+left",
    description: t("Extend region left significantly"),
    active: true,
  },
  {
    id: 4400,
    section: "timeseries",
    element: "ts:grow-right-large",
    label: t("Extend Right (Large)"),
    key: "shift+right",
    description: t("Extend region right significantly"),
    active: true,
  },
  {
    id: 4500,
    section: "timeseries",
    element: "ts:shrink-left-large",
    label: t("Shrink Left (Large)"),
    key: "shift+alt+left",
    description: t("Shrink region from left significantly"),
    active: true,
  },
  {
    id: 4600,
    section: "timeseries",
    element: "ts:shrink-right-large",
    label: t("Shrink Right (Large)"),
    key: "shift+alt+right",
    description: t("Shrink region from right significantly"),
    active: true,
  },

  // Image Gallery Controls
  {
    id: 4700,
    section: "image_gallery",
    element: "image:prev",
    label: t("Previous Image"),
    key: "ctrl+left",
    description: t("View previous image"),
    active: true,
  },
  {
    id: 4800,
    section: "image_gallery",
    element: "image:next",
    label: t("Next Image"),
    key: "ctrl+right",
    description: t("View next image"),
    active: true,
  },

  {
    id: 5000,
    section: "tools",
    element: "tool:zoom-in",
    label: t("Zoom In"),
    key: "ctrl+plus",
    description: t("Zoom in on the image"),
    active: true,
  },
  {
    id: 5100,
    section: "tools",
    element: "tool:pan-image",
    label: t("Pan Image"),
    key: "H",
    description: t("Pan around the image"),
    active: true,
  },
  {
    id: 5200,
    section: "tools",
    element: "tool:zoom-to-fit",
    label: t("Zoom to Fit"),
    key: "shift+1",
    description: t("Zoom to fit the full image in view"),
    active: true,
  },
  {
    id: 5300,
    section: "tools",
    element: "tool:zoom-to-actual",
    label: t("Zoom to 100%"),
    key: "shift+2",
    description: t("Zoom to actual image size (100%)"),
    active: true,
  },
  {
    id: 5400,
    section: "tools",
    element: "tool:zoom-out",
    label: t("Zoom Out"),
    key: "ctrl+minus",
    description: t("Zoom out of the image"),
    active: true,
  },
  {
    id: 5401,
    section: "tools",
    element: "tool:move",
    label: t("Move Tool"),
    key: "V",
    description: t("Select the move tool to reposition annotations"),
    active: true,
  },
  {
    id: 5402,
    section: "tools",
    element: "tool:brush",
    label: t("Brush Tool"),
    key: "B",
    description: t("Select the brush tool"),
    active: true,
  },

  {
    id: 5500,
    section: "tools",
    element: "tool:ellipse",
    label: t("Ellipse Tool"),
    key: "O",
    description: t("Select the ellipse tool"),
    active: true,
  },
  {
    id: 5600,
    section: "tools",
    element: "tool:eraser",
    label: t("Eraser Tool"),
    key: "E",
    description: t("Select the eraser tool"),
    active: true,
  },
  {
    id: 5700,
    section: "tools",
    element: "tool:auto-detect",
    label: t("Auto Detect"),
    key: "M",
    description: t("Use the auto-detect tool to automatically suggest regions"),
    active: true,
  },
  {
    id: 5900,
    section: "tools",
    element: "tool:key-point",
    label: t("Key Point Tool"),
    key: "K",
    description: t("Select the key point annotation tool"),
    active: true,
  },
  {
    id: 6000,
    section: "tools",
    element: "tool:magic-wand",
    label: t("Magic Wand"),
    key: "W",
    description: t("Select the magic wand tool for smart region selection"),
    active: true,
  },
  {
    id: 6100,
    section: "tools",
    element: "tool:polygon",
    label: t("Polygon Tool"),
    key: "P",
    description: t("Select the polygon annotation tool"),
    active: true,
  },
  {
    id: 6200,
    section: "tools",
    element: "tool:rect",
    label: t("Rectangle Tool"),
    key: "R",
    description: t("Select the rectangle annotation tool"),
    active: true,
  },
  {
    id: 6201,
    section: "tools",
    element: "tool:rect-3point",
    label: t("3-Point Rectangle"),
    key: "shift+R",
    description: t("Draw a rotated rectangle using 3-point selection"),
    active: true,
  },

  {
    id: 6300,
    section: "tools",
    element: "tool:rotate-left",
    label: t("Rotate Left"),
    key: "alt+left",
    description: t("Rotate the image 90° to the left"),
    active: true,
  },
  {
    id: 6400,
    section: "tools",
    element: "tool:rotate-right",
    label: t("Rotate Right"),
    key: "alt+right",
    description: t("Rotate the image 90° to the right"),
    active: true,
  },
  {
    id: 6700,
    section: "tools",
    element: "tool:decrease-tool",
    label: t("Decrease Tool Size"),
    key: "[",
    description: t("Decrease tool size"),
    active: true,
  },
  {
    id: 6800,
    section: "tools",
    element: "tool:increase-tool",
    label: t("Increase Tool Size"),
    key: "]",
    description: t("Increase tool size"),
    active: true,
  },

  // Paragraph Navigation
  {
    id: 6900,
    section: "paragraphs",
    element: "phrases:next-phrase",
    label: t("Next Phrase"),
    key: "ctrl+down",
    description: t("Navigate to the next phrase in paragraph view"),
    active: true,
  },
  {
    id: 7000,
    section: "paragraphs",
    element: "phrases:previous-phrase",
    label: t("Previous Phrase"),
    key: "ctrl+up",
    description: t("Navigate to the previous phrase in paragraph view"),
    active: true,
  },
  {
    id: 7100,
    section: "paragraphs",
    element: "phrases:select_all_annotate",
    label: t("Select All and Annotate"),
    key: "ctrl+shift+a",
    description: t("Select all text in current phrase and create annotation"),
    active: true,
  },
  {
    id: 7200,
    section: "paragraphs",
    element: "phrases:next-region",
    label: t("Next Region in Phrase"),
    key: "ctrl+right",
    description: t("Navigate to the next region within current phrase"),
    active: true,
  },
  {
    id: 7300,
    section: "paragraphs",
    element: "phrases:previous-region",
    label: t("Previous Region in Phrase"),
    key: "ctrl+left",
    description: t("Navigate to the previous region within current phrase"),
    active: true,
  },
];

export const HOTKEY_SECTIONS = [
  {
    id: "annotation",
    title: t("Annotation Actions"),
    description: t("Shortcuts for common annotation tasks like submit, skip, undo and redo"),
  },

  {
    id: "data_manager",
    title: t("Data Manager"),
    description: t("Shortcuts for navigating and managing tasks in Project's Data Manager"),
  },

  {
    id: "regions",
    title: t("Region Management"),
    description: t("Shortcuts for creating, selecting and manipulating annotation regions"),
  },

  {
    id: "tools",
    title: t("Tools"),
    description: t("Shortcuts for controlling tools panel when labeling images"),
  },

  {
    id: "audio",
    title: t("Audio Controls"),
    description: t("Shortcuts for controlling audio playback and navigation"),
  },
  {
    id: "video",
    title: t("Video Controls"),
    description: t("Shortcuts for controlling video playback and navigation"),
  },
  {
    id: "timeseries",
    title: t("Time Series Controls"),
    description: t("Shortcuts for manipulating time series data regions"),
  },
  {
    id: "image_gallery",
    title: t("Image Gallery Navigation"),
    description: t("Shortcuts for navigating between images in multi-image tasks"),
  },
  {
    id: "paragraphs",
    title: t("Paragraph Navigation"),
    description: t("Shortcuts for navigating phrases and regions in paragraph/dialogue view"),
  },
];

/**
 * URL patterns mapped to their corresponding hotkey sections
 * Used to automatically determine which shortcuts to display based on current page
 */
export const URL_TO_SECTION_MAPPING = [
  {
    regex: /\/projects\/\d+\/data\/?\?.*task=\d+/i,
    section: ["annotation", "regions"],
  },
  {
    regex: /\/projects\/\d+\/data\/?$/i,
    section: "data_manager",
  },
];
